-- A table with primary key as 1+ autogenerated serial
-- insert other columns not pkey

CREATE TABLE person
( 
   id INT SERIAL PRIMARY KEY,
   name varchar(64),
   age int min check constraint
   gender int check constraint
);


-- A table with primary key generated via a sequence
-- needs a trigger to insert

CREATE TABLE vehicle_type
    - id
    - make
    - model
    - year_of_production

-- 1-m
-- A table with auto-generated uuids as primary key
CREATE TABLE employee_vehicle
 - id
 - vehicle_id
 - employee_id
 - tag


-- now do only serial ids here onewards
CREATE TABLE address
 - id
 - line1
 - street
 - zip
 - city
 - state
 - country default to us


- m-m relation
 CREATE TABLE address_person_association


